INSERT INTO PRODUCTS (NAME, AMOUNT, PRICE) VALUES ('Apples', 5, 1.2);
INSERT INTO PRODUCTS (NAME, AMOUNT, PRICE) VALUES ('Oranges', 15, 1.9);
INSERT INTO PRODUCTS (NAME, AMOUNT, PRICE) VALUES ('Lime', 75, 1.25);
INSERT INTO PRODUCTS (NAME, AMOUNT, PRICE) VALUES ('Banana', 24, 5.7);
COMMIT;